<img src="Pictures/MLimg1.jpg"> <br>
### In this kernel file, we will focus on the "voting"
<a href="https://vitalflux.com/hard-vs-soft-voting-classifier-python-example/#:~:text=Hard%20voting%20classifier%20classifies%20input,classifiers%20are%20equal%20or%20otherwise."> Additional Link 1 </a> <br>
<a href="http://rasbt.github.io/mlxtend/user_guide/classifier/EnsembleVoteClassifier/"> Additional Link 2 </a>

In [213]:
import pandas as pd
from sklearn.datasets import load_iris
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== ==== ======= ===== ====================\n\n    :Missing Attribute Values: None\n    :Class Distribution: 33.3% for each of 3 classes.\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. topic:: References\n\n   - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n     Mathematical Statistics" (John Wiley, NY, 1950).\n   - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n     Structure and Classification Rule for Recognition in Partially Exposed\n     Environments".  IEEE Transactions on Pattern Analysis and Machine\n     Intelligence, Vol. PAMI-2, No. 1, 67-71.\n   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n     on Information Theory, May 1972, 431-433.\n   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n     conceptual clustering system finds 3 classes in the data.\n   - Many, many more ...',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [214]:
X = pd.DataFrame(load_iris()["data"], columns = load_iris()["feature_names"])
X.head(3)

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2

In [215]:
y = pd.DataFrame(load_iris().target)
y.head(3)

   0
0  0
1  0
2  0

In [216]:
load_iris().target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [217]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
y_test

     0
73   1
18   0
118  2
78   1
76   1
31   0
64   1
141  2
68   1
82   1
110  2
12   0
36   0
9    0
19   0

## Voting 1 - Soft Voting Classifier

<img src="https://iq.opengenus.org/content/images/2020/01/ud382N9.png">
<hr>
<img src="http://www.scholarpedia.org/w/images/thumb/8/82/Combining_classifiers2.jpg/450px-Combining_classifiers2.jpg">

In [218]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [219]:
# Gaussian applied separately
clf1 = GaussianNB()
clf1.fit(X_train, y_train)
y_pred1 = clf1.predict(X_test)
accuracy_score(y_pred1, y_test)

C:\Users\99450\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1.0

In [220]:
x1 = clf1.predict_proba(X_test)
x1

array([[2.21535140e-093, 9.97429568e-001, 2.57043221e-003],
       [1.00000000e+000, 4.05073907e-014, 2.58113858e-022],
       [1.52189777e-301, 2.48634681e-012, 1.00000000e+000],
       [1.19525934e-097, 9.83997675e-001, 1.60023251e-002],
       [9.46714185e-110, 8.90075451e-001, 1.09924549e-001],
       [1.00000000e+000, 9.88979001e-014, 9.78784632e-023],
       [1.26635035e-054, 9.99981246e-001, 1.87538163e-005],
       [2.64653928e-183, 9.82346100e-007, 9.99999018e-001],
       [1.46200646e-099, 9.93541781e-001, 6.45821864e-003],
       [3.04989905e-061, 9.99972906e-001, 2.70943450e-005],
       [1.20065145e-157, 5.20315281e-004, 9.99479685e-001],
       [1.00000000e+000, 9.51583157e-018, 4.55765790e-027],
       [1.00000000e+000, 2.65033427e-017, 3.36709962e-026],
       [1.00000000e+000, 2.59461622e-017, 2.01248856e-026],
       [1.00000000e+000, 5.29766695e-017, 1.07184330e-025]])

In [221]:
print(1e-01)
print(1e+2)
print(2e-001)
print(5e+10)

0.1
100.0
0.2
50000000000.0

In [222]:
# Logistic Regression applied separately
clf2 = LogisticRegression(multi_class="multinomial")
clf2.fit(X_train, y_train)
y_pred2 = clf2.predict(X_test)
accuracy_score(y_pred2, y_test)

C:\Users\99450\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1.0

In [223]:
x2 = clf2.predict_proba(X_test)
x2

array([[3.45823921e-03, 8.37194061e-01, 1.59347699e-01],
       [9.49490258e-01, 5.05096312e-02, 1.10738981e-07],
       [4.78976826e-09, 1.09041458e-03, 9.98909581e-01],
       [6.04085876e-03, 7.98280684e-01, 1.95678458e-01],
       [1.28021623e-03, 7.75287507e-01, 2.23432276e-01],
       [9.59496753e-01, 4.05031503e-02, 9.70156311e-08],
       [7.73546543e-02, 9.10300808e-01, 1.23445372e-02],
       [1.25981452e-04, 1.34409673e-01, 8.65464346e-01],
       [2.06117579e-03, 7.59442702e-01, 2.38496122e-01],
       [2.74595859e-02, 9.49674475e-01, 2.28659394e-02],
       [3.67444260e-04, 2.26249816e-01, 7.73382740e-01],
       [9.71459220e-01, 2.85407398e-02, 3.99095337e-08],
       [9.75220778e-01, 2.47792046e-02, 1.72711884e-08],
       [9.65449383e-01, 3.45505593e-02, 5.75536622e-08],
       [9.80989085e-01, 1.90108812e-02, 3.36078547e-08]])

In [224]:
# SVC applied separately
clf3 = SVC(kernel="rbf",degree=3, probability=True)
clf3.fit(X_train, y_train)
y_pred3 = clf3.predict(X_test)
accuracy_score(y_pred3, y_test)

C:\Users\99450\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1.0

In [225]:
# Don't forget to type "probability = True" in the initialization of the model
# Otherwise, it will result in an error
x3 = clf3.predict_proba(X_test)
x3

array([[0.0068995 , 0.89336263, 0.09973788],
       [0.95040215, 0.03459008, 0.01500777],
       [0.0148588 , 0.00195395, 0.98318725],
       [0.00746274, 0.89304349, 0.09949377],
       [0.00930011, 0.78651726, 0.20418262],
       [0.95799007, 0.02999497, 0.01201496],
       [0.02588716, 0.96706354, 0.0070493 ],
       [0.01039071, 0.05870029, 0.930909  ],
       [0.0082195 , 0.77016103, 0.22161947],
       [0.01218317, 0.98151878, 0.00629806],
       [0.009945  , 0.13516406, 0.85489094],
       [0.96841068, 0.02171099, 0.00987833],
       [0.97349247, 0.0167199 , 0.00978762],
       [0.96497558, 0.02468081, 0.0103436 ],
       [0.97314047, 0.01674973, 0.0101098 ]])

In [226]:
soft_voting = VotingClassifier(estimators=[('gnb', clf1), 
                                     ('lr', clf2), 
                                     ('svc', clf3)], voting='soft')
soft_voting.fit(X_train, y_train)
y_pred_soft = soft_voting.predict(X_test)
accuracy_score(y_pred_soft, y_test)

C:\Users\99450\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\99450\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1.0

In [227]:
x4 = soft_voting.predict_proba(X_test)
x4

array([[0.0033643 , 0.91141019, 0.08522551],
       [0.96653354, 0.02844249, 0.00502397],
       [0.00498221, 0.0010046 , 0.9940132 ],
       [0.00440608, 0.89385748, 0.10173644],
       [0.00340577, 0.8205282 , 0.17606603],
       [0.97241653, 0.02355933, 0.00402413],
       [0.03411744, 0.95954085, 0.00634171],
       [0.00353533, 0.06457627, 0.9318884 ],
       [0.00330054, 0.84441667, 0.15228278],
       [0.01305537, 0.97738775, 0.00955688],
       [0.00344807, 0.12150987, 0.87504206],
       [0.97990627, 0.01678387, 0.00330986],
       [0.98286759, 0.01385237, 0.00328004],
       [0.97674833, 0.01978622, 0.00346545],
       [0.98467262, 0.01193962, 0.00338776]])

### Now, let's prove the calculation by analyzing prediction probability for data in 73rd index:
Gaussian NB  - [2.21535140e-093, 9.97429568e-001, 2.57043221e-003] <br>
Logistic Regression   - [3.45823921e-03, 8.37194061e-01, 1.59347699e-01] <br>
Support Vector Classifier  - [0.00627187, 0.91810095, 0.07562718]

<hr>

### Comparing the results with the total probability accomplished by soft voting classifier 
#### We can see that totally everyting is equal with the minor discrepancy which originates from the execution of the models in different time.

In [228]:
# Total probability for the class 0
(x1[0][0] + x2[0][0] + x3[0][0])/3

0.003452578485768802

In [229]:
# Total probability for the class 1
(x1[0][1] + x2[0][1] + x3[0][1])/3

0.9093287523184955

In [230]:
# Total probability for the class 2
(x1[0][2] + x2[0][2] + x3[0][2])/3

0.08721866919573566

In [231]:
x4[0]

array([0.0033643 , 0.91141019, 0.08522551])

<hr>

## Voting 2 - Hard voting classifier

<img src="Pictures/MLimg2.jpg"> <br>

In [232]:
y_pred1

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0])

In [233]:
y_pred2

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0])

In [234]:
y_pred3

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0])

In [235]:
hard_voting = VotingClassifier(estimators=[('gnb', clf1), 
                                     ('lr', clf2), 
                                     ('svc', clf3)], voting='hard')
hard_voting.fit(X_train, y_train)
y_pred_hard = hard_voting.predict(X_test)
y_pred_hard

C:\Users\99450\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\99450\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0])

## Voting 3 - Voting Regressor

<img src="Pictures/MLimg6.jpg">

In [236]:
from sklearn.ensemble import VotingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score

In [238]:
needy_columns = ["Buraxilish ili","Yurush","Qiymet"]
data = turbo[needy_columns].copy()      # Extracted columns
data['Yurush'] = data['Yurush'].str.replace("km","").str.replace(" ","")
data['Yurush'] = data['Yurush'].astype('int64')

currency = data["Qiymet"].apply(lambda x: x.split()[1])
data["currency"] = currency

def exchange_to_AZN(val, curr):
    if curr == "$":
        return int(val)*1.7
    return int(val)

data["Qiymet"] = data["Qiymet"].apply(lambda x: exchange_to_AZN(x.split()[0], x.split()[1]))
data.drop(["currency"], axis = 1, inplace = True)
data.head()

   Buraxilish ili  Yurush   Qiymet
0            1999  366000  12500.0
1            2014  102000  53550.0
2            2002  469700  11700.0
3            1998  556680   9700.0
4            2000  300000  12700.0

In [239]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [240]:
# Linear Regression separately
reg1 = LinearRegression()
reg1.fit(X_train, y_train)
reg1.score(X_test, y_test)

0.7760396570534889

In [241]:
# Support Vector Regressor separately
reg2 = SVR(kernel="rbf",degree=3)
reg2.fit(X_train, y_train)
reg2.score(X_test, y_test)

-0.0507519516837891

In [242]:
# KNeighbors Regressor separately
reg3 = KNeighborsRegressor(n_neighbors = 7)
reg3.fit(X_train, y_train)
reg3.score(X_test, y_test)

0.5675174468323786

In [243]:
voting_reg = VotingRegressor(estimators=[('lr', reg1), 
                                     ('svr', reg2), 
                                     ('knr', reg3)])
voting_reg.fit(X_train, y_train)
voting_reg.score(X_test, y_test)

0.6036660946676597

In [244]:
X_test.head(2)

      Buraxilish ili  Yurush
1201            1998  360395
115             2001  230000

In [245]:
y_test.head(2)

1201    11500.0
115     12400.0
Name: Qiymet, dtype: float64

In [246]:
ent = X_test.head(1)
print(reg1.predict(ent))
print(reg2.predict(ent))
print(reg3.predict(ent))
print(voting_reg.predict(ent))

[10365.27697254]
[11483.95644401]
[10042.85714286]
[10630.69685314]

In [247]:
(reg1.predict(ent) + reg2.predict(ent) + reg3.predict(ent))/3

array([10630.69685314])

In [248]:
(reg1.predict(ent) + reg2.predict(ent) + reg3.predict(ent))/3 == voting_reg.predict(ent)

array([ True])