<img src="Pictures/MLimg3.jpg">
<hr>
<img src="Pictures/MLimg4.jpg">
<hr>

What is bagging and Boosting in data science? <br>
 - Bagging gives equal weight to each model, whereas in Boosting technique, the new models are weighted based on their results.

# Bagging

<img src="Pictures/MLimg5.jpg">
Various models are built parallel on various samples and then the various models <b> vote </b> to give the final model and hence prediction.

The best example for bagging is the "random forest" model which takes different random samples and apply DecisionTree for 'n' time. Then, the result is evaluated by the help of voting.

#### In bagging, a random sample of data in a training set is selected with replacement—meaning that the individual data points can be chosen more than once. However, in pasting, a sample is chosen once in the execution.

# Boosting

<a href="https://www.youtube.com/watch?v=R5FB1ZUejXM"> Look at the difference among CatBoost, XGBoost and LightGBM </a>

In [11]:
import pandas as pd

turbo = pd.read_csv("../ML_Datasets/turboaz.csv")
needy_columns = ["Buraxilish ili","Yurush","Qiymet"]
data = turbo[needy_columns].copy()      # Extracted columns
data['Yurush'] = data['Yurush'].str.replace("km","").str.replace(" ","")
data['Yurush'] = data['Yurush'].astype('int64')

currency = data["Qiymet"].apply(lambda x: x.split()[1])
data["currency"] = currency

def exchange_to_AZN(val, curr):
    if curr == "$":
        return int(val)*1.7
    return int(val)

data["Qiymet"] = data["Qiymet"].apply(lambda x: exchange_to_AZN(x.split()[0], x.split()[1]))
data.drop(["currency"], axis = 1, inplace = True)
regression_data = data.copy()
regression_data.head(3)

   Buraxilish ili  Yurush   Qiymet
0            1999  366000  12500.0
1            2014  102000  53550.0
2            2002  469700  11700.0

In [12]:
from sklearn.model_selection import train_test_split
Xr = regression_data.iloc[:,:-1]
yr = regression_data.iloc[:,-1]
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(Xr, yr, test_size=0.1, random_state=42)

In [13]:
class_data = pd.read_csv("../ML_Datasets/UCI_Credit_Card.csv")
class_data.drop(["ID"], axis=1, inplace=True)
class_data.head(2)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,20000.0,2,2,1,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,2,2,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1

In [18]:
Xc = class_data.iloc[:, 0:23]
yc = class_data.iloc[:, -1]
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(Xc, yc, test_size=0.1, random_state=42)

### LightGBM

In [19]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\99450\anaconda3\lib\site-packages (3.3.4)
Requirement already satisfied: numpy in c:\users\99450\anaconda3\lib\site-packages (from lightgbm) (1.21.5)
Requirement already satisfied: scipy in c:\users\99450\anaconda3\lib\site-packages (from lightgbm) (1.7.3)
Requirement already satisfied: wheel in c:\users\99450\anaconda3\lib\site-packages (from lightgbm) (0.37.1)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\99450\anaconda3\lib\site-packages (from lightgbm) (1.0.2)
Requirement already satisfied: joblib>=0.11 in c:\users\99450\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\99450\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (2.2.0)

In [20]:
from lightgbm import LGBMRegressor
model = LGBMRegressor()
model.fit(X_train_r, y_train_r)
model.score(X_test_r, y_test_r)

0.8587564983313112

In [21]:
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score
model = LGBMClassifier()
model.fit(X_train_c, y_train_c)
y_pred = model.predict(X_test_c)
accuracy_score(y_pred, y_test_c)

0.8216666666666667

### XGBoost

In [22]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\99450\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: scipy in c:\users\99450\anaconda3\lib\site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in c:\users\99450\anaconda3\lib\site-packages (from xgboost) (1.21.5)

In [23]:
import xgboost
print(xgboost.__version__)

1.6.1

In [24]:
from xgboost import XGBClassifier
help(XGBClassifier)

Help on class XGBClassifier in module xgboost.sklearn:

class XGBClassifier(XGBModel, sklearn.base.ClassifierMixin)
 |  XGBClassifier(*, objective: Union[str, Callable[[numpy.ndarray, numpy.ndarray], Tuple[numpy.ndarray, numpy.ndarray]], NoneType] = 'binary:logistic', use_label_encoder: bool = False, **kwargs: Any) -> None
 |
 |  Implementation of the scikit-learn API for XGBoost classification.
 |
 |
 |  Parameters
 |  ----------
 |
 |      n_estimators : int
 |          Number of boosting rounds.
 |
 |      max_depth :  Optional[int]
 |          Maximum tree depth for base learners.
 |      max_leaves :
 |          Maximum number of leaves; 0 indicates no limit.
 |      max_bin :
 |          If using histogram-based algorithm, maximum number of bins per feature
 |      grow_policy :
 |          Tree growing policy. 0: favor splitting at nodes closest to the node, i.e. grow
 |          depth-wise. 1: favor splitting at nodes with highest loss change.
 |      learning_rate : Optional[float]
 |          Boosting learning rate (xgb's "eta")
 |      verbosity : Optional[int]
 |          The degree of verbosity. Valid values are 0 (silent) - 3 (debug).
 |      objective : typing.Union[str, typing.Callable[[numpy.ndarray, numpy.ndarray], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]
 |          Specify the learning task and the corresponding learning objective or
 |          a custom objective function to be used (see note below).
 |      booster: Optional[str]
 |          Specify which booster to use: gbtree, gblinear or dart.
 |      tree_method: Optional[str]
 |          Specify which tree method to use.  Default to auto.  If this parameter is set to
 |          default, XGBoost will choose the most conservative option available.  It's
 |          recommended to study this option from the parameters document :doc:`tree method
 |          </treemethod>`
 |      n_jobs : Optional[int]
 |          Number of parallel threads used to run xgboost.  When used with other Scikit-Learn
 |          algorithms like grid search, you may choose which algorithm to parallelize and
 |          balance the threads.  Creating thread contention will significantly slow down both
 |          algorithms.
 |      gamma : Optional[float]
 |          (min_split_loss) Minimum loss reduction required to make a further partition on a
 |          leaf node of the tree.
 |      min_child_weight : Optional[float]
 |          Minimum sum of instance weight(hessian) needed in a child.
 |      max_delta_step : Optional[float]
 |          Maximum delta step we allow each tree's weight estimation to be.
 |      subsample : Optional[float]
 |          Subsample ratio of the training instance.
 |      sampling_method :
 |          Sampling method. Used only by `gpu_hist` tree method.
 |            - `uniform`: select random training instances uniformly.
 |            - `gradient_based` select random training instances with higher probability when
 |              the gradient and hessian are larger. (cf. CatBoost)
 |      colsample_bytree : Optional[float]
 |          Subsample ratio of columns when constructing each tree.
 |      colsample_bylevel : Optional[float]
 |          Subsample ratio of columns for each level.
 |      colsample_bynode : Optional[float]
 |          Subsample ratio of columns for each split.
 |      reg_alpha : Optional[float]
 |          L1 regularization term on weights (xgb's alpha).
 |      reg_lambda : Optional[float]
 |          L2 regularization term on weights (xgb's lambda).
 |      scale_pos_weight : Optional[float]
 |          Balancing of positive and negative weights.
 |      base_score : Optional[float]
 |          The initial prediction score of all instances, global bias.
 |      random_state : Optional[Union[numpy.random.RandomState, int]]
 |          Random number seed.
 |
 |          .. note::
 |
 |             Using gblinear booster with shotgun updater is nondeterministic as
 |             it uses Hogwild algorithm.
 |
 |      missing : float, default np.nan
 |          Value in the data which needs to be present as a missing value.
 |      num_parallel_tree: Optional[int]
 |          Used for boosting random forest.
 |      monotone_constraints : Optional[Union[Dict[str, int], str]]
 |          Constraint of variable monotonicity.  See :doc:`tutorial </tutorials/monotonic>`
 |          for more information.
 |      interaction_constraints : Optional[Union[str, List[Tuple[str]]]]
 |          Constraints for interaction representing permitted interactions.  The
 |          constraints must be specified in the form of a nested list, e.g. ``[[0, 1], [2,
 |          3, 4]]``, where each inner list is a group of indices of features that are
 |          allowed to interact with each other.  See :doc:`tutorial
 |          </tutorials/feature_interaction_constraint>` for more information
 |      importance_type: Optional[str]
 |          The feature importance type for the feature_importances\_ property:
 |
 |          * For tree model, it's either "gain", "weight", "cover", "total_gain" or
 |            "total_cover".
 |          * For linear model, only "weight" is defined and it's the normalized coefficients
 |            without bias.
 |
 |      gpu_id : Optional[int]
 |          Device ordinal.
 |      validate_parameters : Optional[bool]
 |          Give warnings for unknown parameter.
 |      predictor : Optional[str]
 |          Force XGBoost to use specific predictor, available choices are [cpu_predictor,
 |          gpu_predictor].
 |      enable_categorical : bool
 |
 |          .. versionadded:: 1.5.0
 |
 |          .. note:: This parameter is experimental
 |
 |          Experimental support for categorical data.  When enabled, cudf/pandas.DataFrame
 |          should be used to specify categorical data type.  Also, JSON/UBJSON
 |          serialization format is required.
 |
 |      max_cat_to_onehot : Optional[int]
 |
 |          .. versionadded:: 1.6.0
 |
 |          .. note:: This parameter is experimental
 |
 |          A threshold for deciding whether XGBoost should use one-hot encoding based split
 |          for categorical data.  When number of categories is lesser than the threshold
 |          then one-hot encoding is chosen, otherwise the categories will be partitioned
 |          into children nodes.  Only relevant for regression and binary classification.
 |          See :doc:`Categorical Data </tutorials/categorical>` for details.
 |
 |      eval_metric : Optional[Union[str, List[str], Callable]]
 |
 |          .. versionadded:: 1.6.0
 |
 |          Metric used for monitoring the training result and early stopping.  It can be a
 |          string or list of strings as names of predefined metric in XGBoost (See
 |          doc/parameter.rst), one of the metrics in :py:mod:`sklearn.metrics`, or any other
 |          user defined metric that looks like `sklearn.metrics`.
 |
 |          If custom objective is also provided, then custom metric should implement the
 |          corresponding reverse link function.
 |
 |          Unlike the `scoring` parameter commonly used in scikit-learn, when a callable
 |          object is provided, it's assumed to be a cost function and by default XGBoost will
 |          minimize the result during early stopping.
 |
 |          For advanced usage on Early stopping like directly choosing to maximize instead of
 |          minimize, see :py:obj:`xgboost.callback.EarlyStopping`.
 |
 |          See :doc:`Custom Objective and Evaluation Metric </tutorials/custom_metric_obj>`
 |          for more.
 |
 |          .. note::
 |
 |               This parameter replaces `eval_metric` in :py:meth:`fit` method.  The old one
 |               receives un-transformed prediction regardless of whether custom objective is
 |               being used.
 |
 |          .. code-block:: python
 |
 |              from sklearn.datasets import load_diabetes
 |              from sklearn.metrics import mean_absolute_error
 |              X, y = load_diabetes(return_X_y=True)
 |              reg = xgb.XGBRegressor(
 |                  tree_method="hist",
 |                  eval_metric=mean_absolute_error,
 |              )
 |              reg.fit(X, y, eval_set=[(X, y)])
 |
 |      early_stopping_rounds : Optional[int]
 |
 |          .. versionadded:: 1.6.0
 |
 |          Activates early stopping. Validation metric needs to improve at least once in
 |          every **early_stopping_rounds** round(s) to continue training.  Requires at least
 |          one item in **eval_set** in :py:meth:`fit`.
 |
 |          The method returns the model from the last iteration (not the best one).  If
 |          there's more than one item in **eval_set**, the last entry will be used for early
 |          stopping.  If there's more than one metric in **eval_metric**, the last metric
 |          will be used for early stopping.
 |
 |          If early stopping occurs, the model will have three additional fields:
 |          :py:attr:`best_score`, :py:attr:`best_iteration` and
 |          :py:attr:`best_ntree_limit`.
 |
 |          .. note::
 |
 |              This parameter replaces `early_stopping_rounds` in :py:meth:`fit` method.
 |
 |      callbacks : Optional[List[TrainingCallback]]
 |          List of callback functions that are applied at end of each iteration.
 |          It is possible to use predefined callbacks by using
 |          :ref:`Callback API <callback_api>`.
 |
 |          .. note::
 |
 |             States in callback are not preserved during training, which means callback
 |             objects can not be reused for multiple training sessions without
 |             reinitialization or deepcopy.
 |
 |          .. code-block:: python
 |
 |              for params in parameters_grid:
 |                  # be sure to (re)initialize the callbacks before each run
 |                  callbacks = [xgb.callback.LearningRateScheduler(custom_rates)]
 |                  xgboost.train(params, Xy, callbacks=callbacks)
 |
 |      kwargs : dict, optional
 |          Keyword arguments for XGBoost Booster object.  Full documentation of parameters
 |          can be found :doc:`here </parameter>`.
 |          Attempting to set a parameter via the constructor args and \*\*kwargs
 |          dict simultaneously will result in a TypeError.
 |
 |          .. note:: \*\*kwargs unsupported by scikit-learn
 |
 |              \*\*kwargs is unsupported by scikit-learn.  We do not guarantee
 |              that parameters passed via this argument will interact properly
 |              with scikit-learn.
 |
 |          .. note::  Custom objective function
 |
 |              A custom objective function can be provided for the ``objective``
 |              parameter. In this case, it should have the signature
 |              ``objective(y_true, y_pred) -> grad, hess``:
 |
 |              y_true: array_like of shape [n_samples]
 |                  The target values
 |              y_pred: array_like of shape [n_samples]
 |                  The predicted values
 |
 |              grad: array_like of shape [n_samples]
 |                  The value of the gradient for each sample point.
 |              hess: array_like of shape [n_samples]
 |                  The value of the second derivative for each sample point
 |
 |  Method resolution order:
 |      XGBClassifier
 |      XGBModel
 |      sklearn.base.BaseEstimator
 |      sklearn.base.ClassifierMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, objective: Union[str, Callable[[numpy.ndarray, numpy.ndarray], Tuple[numpy.ndarray, numpy.ndarray]], NoneType] = 'binary:logistic', use_label_encoder: bool = False, **kwargs: Any) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X: Any, y: Any, *, sample_weight: Optional[Any] = None, base_margin: Optional[Any] = None, eval_set: Optional[Sequence[Tuple[Any, Any]]] = None, eval_metric: Union[str, Sequence[str], Callable[[numpy.ndarray, xgboost.core.DMatrix], Tuple[str, float]], NoneType] = None, early_stopping_rounds: Optional[int] = None, verbose: Optional[bool] = True, xgb_model: Union[xgboost.core.Booster, str, xgboost.sklearn.XGBModel, NoneType] = None, sample_weight_eval_set: Optional[Sequence[Any]] = None, base_margin_eval_set: Optional[Sequence[Any]] = None, feature_weights: Optional[Any] = None, callbacks: Optional[Sequence[xgboost.callback.TrainingCallback]] = None) -> 'XGBClassifier'
 |      Fit gradient boosting classifier.
 |
 |      Note that calling ``fit()`` multiple times will cause the model object to be
 |      re-fit from scratch. To resume training from a previous checkpoint, explicitly
 |      pass ``xgb_model`` argument.
 |
 |      Parameters
 |      ----------
 |      X :
 |          Feature matrix
 |      y :
 |          Labels
 |      sample_weight :
 |          instance weights
 |      base_margin :
 |          global bias for each instance.
 |      eval_set :
 |          A list of (X, y) tuple pairs to use as validation sets, for which
 |          metrics will be computed.
 |          Validation metrics will help us track the performance of the model.
 |
 |      eval_metric : str, list of str, or callable, optional
 |          .. deprecated:: 1.6.0
 |              Use `eval_metric` in :py:meth:`__init__` or :py:meth:`set_params` instead.
 |
 |      early_stopping_rounds : int
 |          .. deprecated:: 1.6.0
 |              Use `early_stopping_rounds` in :py:meth:`__init__` or
 |              :py:meth:`set_params` instead.
 |      verbose :
 |          If `verbose` and an evaluation set is used, writes the evaluation metric
 |          measured on the validation set to stderr.
 |      xgb_model :
 |          file name of stored XGBoost model or 'Booster' instance XGBoost model to be
 |          loaded before training (allows training continuation).
 |      sample_weight_eval_set :
 |          A list of the form [L_1, L_2, ..., L_n], where each L_i is an array like
 |          object storing instance weights for the i-th validation set.
 |      base_margin_eval_set :
 |          A list of the form [M_1, M_2, ..., M_n], where each M_i is an array like
 |          object storing base margin for the i-th validation set.
 |      feature_weights :
 |          Weight for each feature, defines the probability of each feature being
 |          selected when colsample is being used.  All values must be greater than 0,
 |          otherwise a `ValueError` is thrown.
 |
 |      callbacks :
 |          .. deprecated:: 1.6.0
 |              Use `callbacks` in :py:meth:`__init__` or :py:meth:`set_params` instead.
 |
 |  predict(self, X: Any, output_margin: bool = False, ntree_limit: Optional[int] = None, validate_features: bool = True, base_margin: Optional[Any] = None, iteration_range: Optional[Tuple[int, int]] = None) -> numpy.ndarray
 |      Predict with `X`.  If the model is trained with early stopping, then `best_iteration`
 |      is used automatically.  For tree models, when data is on GPU, like cupy array or
 |      cuDF dataframe and `predictor` is not specified, the prediction is run on GPU
 |      automatically, otherwise it will run on CPU.
 |
 |      .. note:: This function is only thread safe for `gbtree` and `dart`.
 |
 |      Parameters
 |      ----------
 |      X :
 |          Data to predict with.
 |      output_margin :
 |          Whether to output the raw untransformed margin value.
 |      ntree_limit :
 |          Deprecated, use `iteration_range` instead.
 |      validate_features :
 |          When this is True, validate that the Booster's and data's feature_names are
 |          identical.  Otherwise, it is assumed that the feature_names are the same.
 |      base_margin :
 |          Margin added to prediction.
 |      iteration_range :
 |          Specifies which layer of trees are used in prediction.  For example, if a
 |          random forest is trained with 100 rounds.  Specifying ``iteration_range=(10,
 |          20)``, then only the forests built during [10, 20) (half open set) rounds are
 |          used in this prediction.
 |
 |          .. versionadded:: 1.4.0
 |
 |      Returns
 |      -------
 |      prediction
 |
 |  predict_proba(self, X: Any, ntree_limit: Optional[int] = None, validate_features: bool = True, base_margin: Optional[Any] = None, iteration_range: Optional[Tuple[int, int]] = None) -> numpy.ndarray
 |      Predict the probability of each `X` example being of a given class.
 |
 |      .. note:: This function is only thread safe for `gbtree` and `dart`.
 |
 |      Parameters
 |      ----------
 |      X : array_like
 |          Feature matrix.
 |      ntree_limit : int
 |          Deprecated, use `iteration_range` instead.
 |      validate_features : bool
 |          When this is True, validate that the Booster's and data's feature_names are
 |          identical.  Otherwise, it is assumed that the feature_names are the same.
 |      base_margin : array_like
 |          Margin added to prediction.
 |      iteration_range :
 |          Specifies which layer of trees are used in prediction.  For example, if a
 |          random forest is trained with 100 rounds.  Specifying `iteration_range=(10,
 |          20)`, then only the forests built during [10, 20) (half open set) rounds are
 |          used in this prediction.
 |
 |      Returns
 |      -------
 |      prediction :
 |          a numpy array of shape array-like of shape (n_samples, n_classes) with the
 |          probability of each data example being of a given class.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from XGBModel:
 |
 |  __sklearn_is_fitted__(self) -> bool
 |
 |  apply(self, X: Any, ntree_limit: int = 0, iteration_range: Optional[Tuple[int, int]] = None) -> numpy.ndarray
 |      Return the predicted leaf every tree for each sample. If the model is trained with
 |      early stopping, then `best_iteration` is used automatically.
 |
 |      Parameters
 |      ----------
 |      X : array_like, shape=[n_samples, n_features]
 |          Input features matrix.
 |
 |      iteration_range :
 |          See :py:meth:`predict`.
 |
 |      ntree_limit :
 |          Deprecated, use ``iteration_range`` instead.
 |
 |      Returns
 |      -------
 |      X_leaves : array_like, shape=[n_samples, n_trees]
 |          For each datapoint x in X and for each tree, return the index of the
 |          leaf x ends up in. Leaves are numbered within
 |          ``[0; 2**(self.max_depth+1))``, possibly with gaps in the numbering.
 |
 |  evals_result(self) -> Dict[str, Dict[str, List[float]]]
 |      Return the evaluation results.
 |
 |      If **eval_set** is passed to the :py:meth:`fit` function, you can call
 |      ``evals_result()`` to get evaluation results for all passed **eval_sets**.  When
 |      **eval_metric** is also passed to the :py:meth:`fit` function, the
 |      **evals_result** will contain the **eval_metrics** passed to the :py:meth:`fit`
 |      function.
 |
 |      The returned evaluation result is a dictionary:
 |
 |      .. code-block:: python
 |
 |          {'validation_0': {'logloss': ['0.604835', '0.531479']},
 |           'validation_1': {'logloss': ['0.41965', '0.17686']}}
 |
 |      Returns
 |      -------
 |      evals_result
 |
 |  get_booster(self) -> xgboost.core.Booster
 |      Get the underlying xgboost Booster of this model.
 |
 |      This will raise an exception when fit was not called
 |
 |      Returns
 |      -------
 |      booster : a xgboost booster of underlying model
 |
 |  get_num_boosting_rounds(self) -> int
 |      Gets the number of xgboost boosting rounds.
 |
 |  get_params(self, deep: bool = True) -> Dict[str, Any]
 |      Get parameters.
 |
 |  get_xgb_params(self) -> Dict[str, Any]
 |      Get xgboost specific parameters.
 |
 |  load_model(self, fname: Union[str, bytearray, os.PathLike]) -> None

In [25]:
xgbt = XGBClassifier(max_depth = 2,
             learning_rate = 0.2,
             objective  = "multi:softmax",
             num_class = 2,
             booster = "gbtree",
             n_estimarors = 10,
             random_state = 123)

xgbt.fit(X_train_c, y_train_c)
xgbt_pred = xgbt.predict(X_test_c)
accuracy_score(xgbt_pred, y_test_c)

[00:47:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.6.0/src/learner.cc:627:
Parameters: { "n_estimarors" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.

0.8203333333333334

In [26]:
from xgboost import XGBRegressor
model = XGBRegressor()
model.fit(X_train_r, y_train_r)
model.score(X_test_r, y_test_r)

0.9237046556412684

### CatBoost

In [28]:
!pip install catboost

Collecting CatBoost
  Downloading catboost-1.1.1-cp39-none-win_amd64.whl (74.0 MB)
Collecting graphviz
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
Requirement already satisfied: scipy in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (1.7.3)
Requirement already satisfied: matplotlib in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (3.5.1)
Requirement already satisfied: numpy>=1.16.0 in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (1.21.5)
Requirement already satisfied: six in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (1.16.0)
Requirement already satisfied: plotly in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (5.6.0)
Requirement already satisfied: pandas>=0.24.0 in c:\users\99450\anaconda3\lib\site-packages (from CatBoost) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\99450\anaconda3\lib\site-packages (from pandas>=0.24.0->CatBoost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\99450\anaconda3\lib\site-packages (from pandas>=0.24.0->CatBoost) (2021.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (9.0.1)
Requirement already satisfied: packaging>=20.0 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (3.0.4)
Requirement already satisfied: cycler>=0.10 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\99450\anaconda3\lib\site-packages (from matplotlib->CatBoost) (1.3.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\99450\anaconda3\lib\site-packages (from plotly->CatBoost) (8.0.1)
Installing collected packages: graphviz, CatBoost
Successfully installed CatBoost-1.1.1 graphviz-0.20.1

In [29]:
from catboost import CatBoostRegressor
model = CatBoostRegressor(iterations=2,
                          learning_rate=1,
                          depth=2)
model.fit(X_train_r, y_train_r)
model.score(X_test_r, y_test_r)

0:	learn: 5800.7106697	total: 113ms	remaining: 113ms
1:	learn: 4081.1339042	total: 114ms	remaining: 0us

0.8891598466914072